#include "telecoil_filter.h"
#include "unity.h"

#include <stddef.h>
#include <stdint.h>

/*
 * These filter tests intentionally avoid libm so the embedded Testing build
 * does not require an extra -lm linker setting. Sine waves are generated by
 * a numerically stable complex-oscillator recurrence using precomputed
 * sin/cos increments for the test frequencies.
 */

static float abs_float(float value)
{
    return (value < 0.0f) ? -value : value;
}

static float measure_power_ratio(uint32_t fs,
                                 float cos_step,
                                 float sin_step)
{
    TelecoilFilter_t filter;
    if (!TelecoilFilter_Init(&filter, fs)) {
        return -1.0f;
    }

    const size_t total = 4096U;
    const size_t skip = 1024U;
    double input_energy = 0.0;
    double output_energy = 0.0;

    /* sin(0)=0, cos(0)=1. */
    float sine = 0.0f;
    float cosine = 1.0f;

    for (size_t i = 0U; i < total; ++i) {
        const float input = sine;
        const float output = TelecoilFilter_ProcessSample(&filter, input);

        if (i >= skip) {
            input_energy += (double)input * (double)input;
            output_energy += (double)output * (double)output;
        }

        const float next_sine = (sine * cos_step) + (cosine * sin_step);
        const float next_cosine = (cosine * cos_step) - (sine * sin_step);
        sine = next_sine;
        cosine = next_cosine;
    }

    if (input_energy <= 0.0) {
        return 0.0f;
    }
    return (float)(output_energy / input_energy);
}

static void test_init_accepts_16k(void)
{
    TelecoilFilter_t filter;
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&filter, 16000U));
    TEST_ASSERT_TRUE(filter.initialised);
}

static void test_init_accepts_48k(void)
{
    TelecoilFilter_t filter;
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&filter, 48000U));
}

static void test_init_rejects_unsupported_rate(void)
{
    TelecoilFilter_t filter;
    TEST_ASSERT_FALSE(TelecoilFilter_Init(&filter, 44100U));
}

static void test_uninitialised_filter_returns_zero(void)
{
    TelecoilFilter_t filter = {0};
    TEST_ASSERT_FLOAT_WITHIN(0.000001f, 0.0f, TelecoilFilter_ProcessSample(&filter, 1.0f));
}

static void test_1khz_is_passed_at_16k(void)
{
    const float power_ratio = measure_power_ratio(16000U, 0.9238795325f, 0.3826834324f);
    TEST_ASSERT_GREATER_THAN(0.81f, power_ratio); /* amplitude gain > 0.90 */
    TEST_ASSERT_LESS_THAN(1.21f, power_ratio);   /* amplitude gain < 1.10 */
}

static void test_50hz_is_strongly_rejected_at_16k(void)
{
    const float power_ratio = measure_power_ratio(16000U, 0.9998072405f, 0.0196336925f);
    TEST_ASSERT_LESS_THAN(0.0016f, power_ratio); /* amplitude gain < 0.04 */
}

static void test_7khz_is_rejected_at_16k(void)
{
    const float power_ratio = measure_power_ratio(16000U, -0.9238795325f, 0.3826834324f);
    TEST_ASSERT_LESS_THAN(0.01f, power_ratio);   /* amplitude gain < 0.10 */
}

static void test_1khz_is_passed_at_48k(void)
{
    const float power_ratio = measure_power_ratio(48000U, 0.9914448614f, 0.1305261922f);
    TEST_ASSERT_GREATER_THAN(0.81f, power_ratio);
    TEST_ASSERT_LESS_THAN(1.21f, power_ratio);
}

static void test_50hz_is_strongly_rejected_at_48k(void)
{
    const float power_ratio = measure_power_ratio(48000U, 0.9999785817f, 0.0065449380f);
    TEST_ASSERT_LESS_THAN(0.0016f, power_ratio);
}

static void test_12khz_is_rejected_at_48k(void)
{
    const float power_ratio = measure_power_ratio(48000U, 0.0f, 1.0f);
    TEST_ASSERT_LESS_THAN(0.0144f, power_ratio);  /* amplitude gain < 0.12 */
}

static void test_dc_response_decays_near_zero(void)
{
    TelecoilFilter_t filter;
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&filter, 48000U));
    float output = 0.0f;
    for (size_t i = 0U; i < 4000U; ++i) {
        output = TelecoilFilter_ProcessSample(&filter, 1.0f);
    }
    TEST_ASSERT_LESS_THAN(0.001f, abs_float(output));
}

static void test_impulse_response_is_stable(void)
{
    TelecoilFilter_t filter;
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&filter, 48000U));
    float output = TelecoilFilter_ProcessSample(&filter, 1.0f);
    for (size_t i = 0U; i < 3000U; ++i) {
        output = TelecoilFilter_ProcessSample(&filter, 0.0f);
    }
    TEST_ASSERT_LESS_THAN(0.0001f, abs_float(output));
}

static void test_reset_reproduces_same_impulse_start(void)
{
    TelecoilFilter_t filter;
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&filter, 16000U));
    const float first = TelecoilFilter_ProcessSample(&filter, 1.0f);
    (void)TelecoilFilter_ProcessSample(&filter, 0.0f);
    TelecoilFilter_Reset(&filter);
    const float after_reset = TelecoilFilter_ProcessSample(&filter, 1.0f);
    TEST_ASSERT_FLOAT_WITHIN(0.000001f, first, after_reset);
}

static void test_block_processing_validates_pointers(void)
{
    TelecoilFilter_t filter;
    float data[2] = {0.0f, 0.0f};
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&filter, 16000U));
    TEST_ASSERT_FALSE(TelecoilFilter_ProcessBlock(&filter, NULL, data, 2U));
}

static void test_zero_length_block_is_allowed(void)
{
    TelecoilFilter_t filter;
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&filter, 16000U));
    TEST_ASSERT_TRUE(TelecoilFilter_ProcessBlock(&filter, NULL, NULL, 0U));
}

static void test_init_rejects_null_filter(void)
{
    TEST_ASSERT_FALSE(TelecoilFilter_Init(NULL, 16000U));
}

static void test_reset_accepts_null_filter(void)
{
    TelecoilFilter_Reset(NULL);
    TEST_ASSERT_TRUE(true);
}

static void test_block_processing_rejects_uninitialised_filter(void)
{
    TelecoilFilter_t filter = {0};
    float input[2] = {1.0f, 0.0f};
    float output[2] = {0.0f, 0.0f};
    TEST_ASSERT_FALSE(TelecoilFilter_ProcessBlock(&filter, input, output, 2U));
}

static void test_block_processing_produces_same_samples_as_sample_api(void)
{
    TelecoilFilter_t block_filter;
    TelecoilFilter_t sample_filter;
    const float input[4] = {1.0f, 0.0f, -0.5f, 0.25f};
    float output[4] = {0.0f};
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&block_filter, 48000U));
    TEST_ASSERT_TRUE(TelecoilFilter_Init(&sample_filter, 48000U));
    TEST_ASSERT_TRUE(TelecoilFilter_ProcessBlock(&block_filter, input, output, 4U));
    for (size_t i = 0U; i < 4U; ++i) {
        const float expected = TelecoilFilter_ProcessSample(&sample_filter, input[i]);
        TEST_ASSERT_FLOAT_WITHIN(0.000001f, expected, output[i]);
    }
}

void RunTelecoilFilterTests(void)
{
    RUN_TEST(test_init_accepts_16k);
    RUN_TEST(test_init_accepts_48k);
    RUN_TEST(test_init_rejects_unsupported_rate);
    RUN_TEST(test_uninitialised_filter_returns_zero);
    RUN_TEST(test_1khz_is_passed_at_16k);
    RUN_TEST(test_50hz_is_strongly_rejected_at_16k);
    RUN_TEST(test_7khz_is_rejected_at_16k);
    RUN_TEST(test_1khz_is_passed_at_48k);
    RUN_TEST(test_50hz_is_strongly_rejected_at_48k);
    RUN_TEST(test_12khz_is_rejected_at_48k);
    RUN_TEST(test_dc_response_decays_near_zero);
    RUN_TEST(test_impulse_response_is_stable);
    RUN_TEST(test_reset_reproduces_same_impulse_start);
    RUN_TEST(test_block_processing_validates_pointers);
    RUN_TEST(test_zero_length_block_is_allowed);
    RUN_TEST(test_init_rejects_null_filter);
    RUN_TEST(test_reset_accepts_null_filter);
    RUN_TEST(test_block_processing_rejects_uninitialised_filter);
    RUN_TEST(test_block_processing_produces_same_samples_as_sample_api);
}
